version: '3.1'

services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: openmusic
    ports:
      - 5432:5432
    volumes: 
      # copy the sql script to create tables
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  rabbitmq:
    image: rabbitmq:3.11.0-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  
  redis:
    image: redis:7.0.3-alpine
    restart: always
    ports:
      - '6379:6379'